### ISSUE TITLE
Air + heating reports wrong power-usage

### ISSUE THREAD

**Issue by chsw** [visualapproach/WiFi-remote-for-Bestway-Lay-Z-SPA#756] opened 2024-07-12 09:27 UTC
**Hardware (please complete the following information):**
 - Pump model: S100101
 - 4 or 6 wires: 6 wires
 - PCB type Wemos D1 mini
 - Level shifter type,

**Software (please complete the following information):**
 - Version 4.4.1

**Your message**
On this pump (at least the one aimed for the Swedish market) only one of the heaters is active when both the heating and air bubbles are active at the same time. But the power-usage reported is both heat 1 and 2.
According to an external power meter, the heating seems to use about 850w when active at the same time as the bubbles.

**Comment by visualapproach** [comment] 2024-07-15 11:50
Ok, thanks for the info. I think I thought about it when adding the power meters, but decided no one would notice 🫤 
Might have a look later. Thx

**Comment by visualapproach** [comment] 2024-07-15 13:43
Ok, try dev branch and see if it is working now.

**Comment by chsw** [comment] 2024-07-17 19:53
I tried the dev branch. It seems to report a more realistic power usage when using both air and bubbles, but it appears as it affected the energy usage reported (it looks like it only report the correct energy consumed when heating is active).

![image](https://github.com/user-attachments/assets/2edccccc-65f6-4580-a64e-a2cff337b877)

The first drop in the graph showing consumed energy correlates to installing the new firmware.

Unfortunately I also seem to have lost the ability to connect my module to my wifi. As soon as I connect to the layzspa-hotspot and tries to load the page, it reboots. It doesn't allow me to upload a new firmware either, so I haven't been able to verify if this issue is related to the changes made to the ap manager or if it is an hardware issue related to the fact that I run a d1 mini without level-converters.

**Comment by visualapproach** [comment] 2024-07-17 20:01
If it worked before I don't think it's a hardware problem.

**Comment by visualapproach** [comment] 2024-07-18 07:12
The reboot problem is fixed in todays dev version

**Comment by visualapproach** [comment] 2024-07-18 07:30
Reagarding the energy graph. Can you double check this? And compare total kwh vs daily. Not sure what your graph represents.
Thx

**Comment by chsw** [comment] 2024-07-18 08:18
I managed to get it to connect to my wifi this morning, and upload the latest version from dev.
Unfortunately its now "bricked" and I am unable to start the pump at all!
Probably need to physically remove the module and flash it...

**Comment by visualapproach** [comment] 2024-07-18 08:23
Does it not start the access point?

**Comment by visualapproach** [comment] 2024-07-18 08:24
If you uploaded the file system also, you need to do all the settings again.

**Comment by chsw** [comment] 2024-07-18 08:30
I only  uploaded a new firmware (last 5 commits to dev).
No Ap and no response what so ever on the display.

**Comment by chsw** [comment] 2024-07-18 09:12
I have tried to powercycle, but still nothing. I tried the same firmware on a spare esp, and I seem to work there. 
I cant really access the module inside the pump right now though.

**Comment by chsw** [comment] 2024-07-18 13:47
Ok, so if Ap  manager is disabled and it have trouble connecting, it will not forward any data on the lines?
I tried to press power-lock-timer-power to reset the wifi, but that didn't really do anything. 
Seems like I really should enable AP Manager again :)

**Comment by chsw** [comment] 2024-07-18 13:52
About the issue with energy usage:

![image](https://github.com/user-attachments/assets/65c25806-72db-4e1f-952d-865cdeb8d115)

Energy is the energy entity and today the today entity, as shown in Home assistant using mqtt integration.
Today seem to be unaffected, although the 75Kwh usage today is very strange. But since it had trouble this morning connecting, It might have to do with that. 

The (total) energy seem to have two modes. One value which increases when the heater is on (probably the real value). And another value (which also increases over time, but is much smaller) when heater is off.

**Comment by visualapproach** [comment] 2024-07-18 14:08
> Ok, so if Ap manager is disabled and it have trouble connecting, it will not forward any data on the lines? I tried to press power-lock-timer-power to reset the wifi, but that didn't really do anything. Seems like I really should enable AP Manager again :)

I updated the network config page now. It should be more clear what the checkboxes mean.
Basically - do not disable "soft AP".

You should also update to the latest dev firmware, because it will now remember the SSID/pswd even after you upload the file image.

**Comment by visualapproach** [comment] 2024-07-18 14:29
> About the issue with energy usage:
> 
> ![image](https://private-user-images.githubusercontent.com/5528726/349985597-65c25806-72db-4e1f-952d-865cdeb8d115.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzMTI5NTUsIm5iZiI6MTcyMTMxMjY1NSwicGF0aCI6Ii81NTI4NzI2LzM0OTk4NTU5Ny02NWMyNTgwNi03MmRiLTRlMWYtOTUyZC04NjVjZGViOGQxMTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MThUMTQyNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWFiYzMxODlhZDRmOWE3NDFkYjA4MmVkZTk2ZmViMWJiODY4N2NjMWI4NmVjMmJlYWRmMTM5MTA2NDQwZWM4NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n0y-6j-LT_vHWBFp50-umt-3dL8JJ99Qab8whrP0v0I)
> 
> Energy is the energy entity and today the today entity, as shown in Home assistant using mqtt integration. Today seem to be unaffected, although the 75Kwh usage today is very strange. But since it had trouble this morning connecting, It might have to do with that.
> 
> The (total) energy seem to have two modes. One value which increases when the heater is on (probably the real value). And another value (which also increases over time, but is much smaller) when heater is off.

testing

**Comment by visualapproach** [comment] 2024-07-18 14:38
confirmed. WIP

**Comment by visualapproach** [comment] 2024-07-18 14:57
Fixed (dev branch)

**Closed** 2024-09-24 02:04 UTC
Labels: no-issue-activity
